/**
 * 企业微信数据链路 — 链路③④⑤ (前端推送 + 前端下行 + HTTP上报)
 */
(function () {
  'use strict';

  window.WKWX = window.WKWX || {};

  // ================================================================
  //  链路③ 逆向 → 客户端 → 前端（WebSocket推送）
  // ================================================================

  var linkFrontPush = {
    id: 'wkwx_link_front_push',
    name: '③ 逆向 → 客户端 → 前端（WebSocket推送）',
    direction: 'front-up',
    color: '#a5d6a7',
    description: '企微进程的被动事件通过 IPC 回传，经 WkMsgHandlerCenter 处理后由 SendFrontAspect 做企微→前端的类型转换（login/remark/kickout），再通过 WebSocket 推送到前端 UI',
    mermaid: [
      'graph TD',
      '    s0["企微进程 WXWork.exe<br/>被动事件"]',
      '    s1["IPC轮询接收<br/>asyncSelectTask.js"]',
      '    s2["出站分发<br/>dispatchOutBound.js"]',
      '    s3["企微消息处理中心<br/>workWxMsgHandle.js"]',
      '    s4["业务路由<br/>flowSource=FRONT"]',
      '    s5["前端出站处理<br/>frontFlowOutBound.js"]',
      '    s6["企微切面处理<br/>SendFrontAspect"]',
      '    s7["前端UI<br/>Electron渲染进程"]',
      '    s0 -->|"IPC管道"| s1',
      '    s1 -->|"200ms轮询"| s2',
      '    s2 -->|"workWx=true"| s3',
      '    s3 -->|"两段式回执"| s4',
      '    s4 -->|"flowSource=FRONT"| s5',
      '    s5 -->|"SendFrontAspect.beforeSendMessageToFront"| s6',
      '    s6 -->|"WebSocket推送"| s7',
    ].join('\n'),
    ascii: [
      '  WXWork.exe → [IPC管道] → asyncSelectTask.js → dispatchOutBound.js',
      '  → WkMsgHandlerCenter → businessHandler(flowSource=FRONT)',
      '  → frontFlowOutBound.js → SendFrontAspect(3个策略) → sendToFront → [WS] → 前端',
    ].join('\n'),
    nodes: [
      {
        name: '企微进程被动事件（WXWork.exe）',
        icon: 'wechat',
        file: '逆向端 (WXWork.exe IPC)',
        func: '企微进程产生被动事件',
        summary: '企微进程在收到消息、好友变更、群变动等场景产生回调事件',
        arrow: 'IPC管道',
        detail: [
          '产生前端推送的事件类型:',
          '- login: 登录状态变化',
          '- changeremark: 备注修改完成',
          '- delconversationmember: 踢人完成',
          '- userlist: 好友/群列表响应',
          '- 其他: 直接透传到前端的回报消息',
        ].join('\n'),
        dataIn: '企微内部事件',
        dataOut: 'IPC 消息 (JSON)',
        logKeywords: [],
      },
      {
        name: 'IPC轮询接收',
        icon: 'receive',
        file: 'src/msg-center/core/reverse/asyncSelectTask.js',
        func: 'run() → loop() → successIpcConnect()',
        summary: '200ms轮询 IPC 管道，接收企微进程回传的消息',
        arrow: 'dispatchOutBound()',
        detail: '与链路②相同：IpcSelectCltChannel 轮询 → IpcClientRecvMessage 读取 → dispatchOutBound 分发',
        dataIn: 'IPC 管道数据',
        dataOut: 'JSON string message',
        logKeywords: ['asyncSelectTask'],
      },
      {
        name: '出站分发 → WkMsgHandlerCenter',
        icon: 'dispatch',
        file: 'src/msg-center/dispatch-center/dispatchOutBound.js',
        func: 'dispatchOutBound() → WkMsgHandlerCenter.outBoundMsg()',
        summary: 'workWx=true 时路由到 WkMsgHandlerCenter 进行企微消息处理',
        arrow: 'WkMsgHandlerCenter.outBoundMsg()',
        detail: '与链路②相同的出站分发逻辑，区别在于后续 businessHandler 的路由目标不同',
        dataIn: 'JSON string message',
        dataOut: '路由到 WkMsgHandlerCenter',
        logKeywords: ['dispatchOutBound'],
      },
      {
        name: '企微消息处理中心 + 业务路由',
        icon: 'process',
        file: 'src/msg-center/dispatch-center/handle/workWxMsgHandle.js\nsrc/msg-center/dispatch-center/handle/msgHandleBase.js',
        func: 'messageHandler() → businessHandler()',
        summary: '两段式回执匹配后，根据 flowSource=FRONT(1) 路由到 frontFlowOutBound',
        arrow: 'frontFlowOutBound()',
        detail: [
          '【前端链路的 flowSource 来源】',
          '当消息来自前端操作（如前端发起的好友列表请求、发消息等），',
          'frontFlowInBound 标记 flowSource=FRONT(1)，',
          '上行时 businessHandler 路由到 frontFlowOutBound 推送前端',
          '',
          '【不经两段式的直通路径】',
          'isNotContains() 过滤掉非 recvmsg/msgreport/sendmsg_* 的 type',
          '这些类型直接走 cloudFlowOutBound 或 responseMsgHandler',
          '好友列表(userlist)等走 responseMsgHandler → WkUserListResponseMsgHandler',
        ].join('\n'),
        dataIn: '逆向回报 JSON',
        dataOut: '路由到 frontFlowOutBound',
        logKeywords: ['businessHandler', 'frontFlowOutBound'],
      },
      {
        name: '前端出站处理',
        icon: 'monitor',
        file: 'src/msg-center/dispatch-center/dispatch/frontFlowOutBound.js',
        func: 'frontFlowOutBound(message, pipeLineWrapper)',
        summary: '调用 SendFrontAspect.beforeSendMessageToFront() 做企微类型转换，转换后通过 WebSocket 推送前端',
        arrow: 'sendToFront()',
        detail: [
          '【frontFlowOutBound 核心逻辑】',
          'function frontFlowOutBound(message, pipeLineWrapper) {',
          '    const isExit = SendFrontAspect.beforeSendMessageToFront(message, pipeLineWrapper);',
          '    if (jsonObject.type === RECVMSG) return; // 过滤 recvmsg',
          '    if (!isExit) sendToFront(message, id, wxid); // 未被策略拦截则透传',
          '}',
          '',
          '【关键: isExit 的含义】',
          'isExit=true: 消息已被企微策略处理并发送，不再透传',
          'isExit=false: 非企微（个微）或无策略匹配，正常透传',
        ].join('\n'),
        dataIn: '逆向回报消息',
        dataOut: 'WebSocket 推送数据（经企微转换后）',
        logKeywords: ['frontFlowOutBound', 'sendToFront'],
      },
      {
        name: '企微切面处理（SendFrontAspect）',
        icon: 'handler',
        file: 'src/msg-center/business/point-cut/SendFrontAsect.js',
        func: 'beforeSendMessageToFront(message, pipeLineWrapper)',
        summary: '仅对企微生效（workWx=true），遍历 3 个转换策略将企微类型转为前端可识别类型',
        arrow: 'WebSocket → 前端UI',
        detail: [
          '【核心逻辑 SendFrontAsect.js】',
          'beforeSendMessageToFront(message, pipeLineWrapper) {',
          '    if (!pipeLineWrapper.workWx) return false; // 非企微直接跳过',
          '    for (SendMsg2FrontStrategyList) {',
          '        if (strategy.handleMsgToFront(message, pipeLineWrapper)) {',
          '            return true; // 策略已处理，拦截透传',
          '        }',
          '    }',
          '    return false; // 无策略匹配，走正常透传',
          '}',
          '',
          '【3 个企微前端策略 SendMsg2FrontStrategyList】',
          '',
          '① SendLoginMsgFrontStrategy (SendLoginMsgFrontStrategy.js)',
          '   filter: jsonObject.type === "login"',
          '   operate: 转换 login_user 结构:',
          '     login_user.avator_url → headimg',
          '     login_user.gender → sex',
          '     login_user.name → nickname',
          '     login_user.id → wxid',
          '     login_user.verifying_name → verifyingName',
          '',
          '② SendKickOutMsgFrontStrategy (sendKickOutMsgFrontStrategy.js)',
          '   filter: jsonObject.type === "delconversationmember"',
          '   operate: 转换为前端格式:',
          '     type: "delconversationmember" → "delchatmenber"',
          '     conversation → data.to',
          '     array → data.array (id列表)',
          '',
          '③ SendRemarkMsgFrontStrategy (SendRemarkMsgFrontStrategy.js)',
          '   filter: jsonObject.type === "changeremark"',
          '   operate: 转换为前端格式:',
          '     type: "changeremark" → "remark"',
          '     userid → data.to',
          '     remarks → data.content',
          '     corp_remark, remark_url, decription → data.*',
        ].join('\n'),
        dataIn: '企微回报消息 (JSON)',
        dataOut: '转换后的前端消息 → sendToFront()',
        logKeywords: ['SendLoginMsgFrontStrategy', 'SendKickOutMsgFrontStrategy', 'SendRemarkMsgFrontStrategy'],
      },
      {
        name: '前端UI (Electron渲染进程)',
        icon: 'monitor',
        file: 'galaxy/src/entries/menu/store/thunks.js → galaxy/src/entries/sub/store/base/thunks.js',
        func: 'ws.onmessage → dispatch(setNews) → handleNewsBodyTypeForward()',
        summary: '前端通过 WebSocket 接收推送，Menu层分发到 Sub 层，Sub 按 body.type 分发处理',
        arrow: '',
        detail: [
          '【Menu层接收 thunks.js ws.onmessage】',
          'cmdId==="forward" → dispatch(setNews({ news: msg }))',
          '→ webviewSendById 发送 parent-message 到 Sub',
          '',
          '【Sub层处理 base/thunks.js】',
          'handleNewsCmdId → case "forward":',
          '  handleNewsBodyTypeForward(news, body)',
          '  按 body.type 分发: login/logout/userlist/remark 等',
          '',
          '【企微标识】',
          'userInfo.workWx: 从 allConfig 中获取',
          'qyFlag: getGlobalData("qyFlag") 全局标识',
        ].join('\n'),
        dataIn: 'WebSocket 消息',
        dataOut: 'UI 渲染更新',
        logKeywords: [],
      },
    ],
  };

  // ================================================================
  //  链路④ 前端 → 客户端 → 逆向（前端指令下行）
  // ================================================================

  var linkFrontDown = {
    id: 'wkwx_link_front_down',
    name: '④ 前端 → 客户端 → 逆向（前端指令下行）',
    direction: 'front-down',
    color: '#90caf9',
    description: '前端 UI 通过 IPC→Menu→WebSocket 将指令发送到客户端主进程，经 frontFlowInBound 按 cmdId 路由后，dispatchInBound 使用 typeConvert 和 WkTaskCallBack 处理企微类型，最终通过 IPC 下发到 WXWork.exe',
    mermaid: [
      'graph TD',
      '    s0["前端Sub层<br/>ipc.sendToHost"]',
      '    s1["前端Menu层<br/>ws.send"]',
      '    s2["WebSocket接收<br/>frontServer.js"]',
      '    s3["前端入站处理<br/>frontFlowInBound.js"]',
      '    s4["前端任务处理器<br/>frontHandlerMap"]',
      '    s5["入站分发处理<br/>dispatchInBound.js"]',
      '    s6["IPC发送到逆向<br/>reverseSend.js"]',
      '    s7["企微进程<br/>WXWork.exe"]',
      '    s0 -->|"sub-message IPC"| s1',
      '    s1 -->|"WebSocket"| s2',
      '    s2 -->|"onMessage"| s3',
      '    s3 -->|"cmdId路由"| s4',
      '    s4 -->|"构造指令"| s5',
      '    s5 -->|"typeConvert+WkTaskCallBack"| s6',
      '    s6 -->|"IPC管道"| s7',
    ].join('\n'),
    ascii: [
      '  Sub(ipc.sendToHost) → Menu(ws.send) → frontServer.js → frontFlowInBound.js',
      '  → frontHandlerMap[cmdId] → dispatchInBound.js(typeConvert) → reverseSend.js',
      '  → [IPC管道] → WXWork.exe',
    ].join('\n'),
    nodes: [
      {
        name: '前端Sub层发送',
        icon: 'monitor',
        file: 'galaxy/src/entries/sub/store/base/thunks.js',
        func: 'sendMessage(msg, cmdId)',
        lines: '68-87',
        summary: 'Sub 页面通过 ipc.sendToHost("sub-message", { cmdId, body }) 将指令发送给 Menu 层',
        arrow: 'ipc.sendToHost("sub-message")',
        detail: [
          'function sendMessage(msg, cmdId) {',
          '    params.cmdId = cmdId || "forward";',
          '    params.body = msg;',
          '    ipc.sendToHost("sub-message", params);',
          '}',
          '',
          '【常用 cmdId】',
          'forward: 通用转发（默认）',
          'getAllConfig: 获取全量配置',
          'upload: 文件上传',
          'uploadVoice: 语音上传',
          'getMqttStatus: MQTT 状态查询',
        ].join('\n'),
        dataIn: '用户操作事件',
        dataOut: '{ cmdId, body }',
        logKeywords: [],
      },
      {
        name: '前端Menu层转发',
        icon: 'monitor',
        file: 'galaxy/src/entries/menu/App.js → galaxy/src/entries/menu/store/thunks.js',
        func: 'handleWsSend(data) → wsSend(msg)',
        lines: '941-952,506-524',
        summary: 'Menu 监听 sub-message → handleWsSend → ws.send(JSON.stringify(msg)) 发送到客户端 WebSocket',
        arrow: 'WebSocket send()',
        detail: [
          '【App.js 监听 sub-message L941-952】',
          'case "sub-message":',
          '    if (sendNewsType.includes(data.cmdId)) {',
          '        handleWsSend(data);',
          '    }',
          '',
          'sendNewsType = ["getAllConfig","getMqttStatus","forward","upload","uploadVoice"]',
          '',
          '【thunks.js wsSend L506-524】',
          'ws.send(JSON.stringify(msg))',
        ].join('\n'),
        dataIn: '{ cmdId, body }',
        dataOut: 'WebSocket JSON 消息',
        logKeywords: [],
      },
      {
        name: '前端入站处理',
        icon: 'dispatch',
        file: 'src/msg-center/dispatch-center/dispatch/frontFlowInBound.js',
        func: 'frontFlowInBound(message)',
        lines: '17-27',
        summary: '按 cmdId 路由到 frontHandlerMap 中对应的处理函数，企微与个微共用同一套 cmdId 映射',
        arrow: 'frontHandlerMap[cmdId]()',
        detail: [
          '【frontHandlerMap 完整映射 L17-27】',
          '{',
          '  getAllConfig   → getAllConfigTask.js',
          '  upload         → uploadTask.js',
          '  forward        → forwardTask.js ★最常用',
          '  frontLogout    → frontLogoutTask.js',
          '  frontLogin     → frontLoginTask.js',
          '  getMqttStatus  → getMqttConnectionStatusTask.js',
          '  killAll        → killTask.js',
          '  killJava       → killAppTask.js',
          '  reportLogicWorking → reportLogicWorkingTask.js',
          '}',
          '',
          '【与个微的关系】',
          '企微和个微共用同一套 frontHandlerMap，无企微专属 cmdId',
          'forward 是最常用的 cmdId，将消息体直接传递给 dispatchInBound',
        ].join('\n'),
        dataIn: 'WebSocket message (JSON)',
        dataOut: '路由到对应 task-front 处理器',
        logKeywords: ['frontFlowInBound', 'cmdId', 'forwardTask'],
      },
      {
        name: '入站分发处理（企微类型转换）',
        icon: 'dispatch',
        file: 'src/msg-center/dispatch-center/dispatchInBound.js',
        func: 'dispatchInBound() → typeConvert() → processInBoundTask()',
        summary: '与链路①共用同一入站逻辑: typeConvert 将 sendmsg_* 统一转换，WkTaskCallBack 匹配回调关系，加锁后发到逆向',
        arrow: 'reverseSend.sendMessage()',
        detail: [
          '与链路①入站分发处理逻辑完全相同',
          '参见链路①「入站分发处理（含企微类型转换）」节点',
          '',
          '【关键差异: flowSource】',
          '来自前端的消息: flowSource=FRONT(1)',
          '上行回报时路由到 frontFlowOutBound 推送前端',
        ].join('\n'),
        dataIn: 'ClientTask JSON',
        dataOut: '发送到 reverseSend 的 message',
        logKeywords: ['dispatchInBound', 'typeConvert'],
      },
      {
        name: 'IPC发送到逆向',
        icon: 'send',
        file: 'src/msg-center/dispatch-center/reverseSend.js',
        func: 'sendMessage() → pipeLineSend()',
        summary: '通过 IPC 命名管道将前端指令发送到 WXWork.exe 进程',
        arrow: 'IPC管道',
        detail: '与链路①相同: lockKey 去重 → IpcClientSendMessage → PipeCore.dll → WXWork.exe',
        dataIn: 'JSON string',
        dataOut: 'IPC 二进制数据',
        logKeywords: ['pipeLineSend', 'reverseSend'],
      },
      {
        name: '企业微信进程（WXWork.exe）',
        icon: 'wechat',
        file: '逆向端 (WXWork.exe IPC)',
        func: '由企业微信进程内部处理',
        summary: '企微进程接收前端下发的指令并执行',
        arrow: '',
        detail: '接收指令后执行操作，结果通过链路②或③回传',
        dataIn: 'IPC 指令',
        dataOut: '操作执行结果',
        logKeywords: [],
      },
    ],
  };

  // ================================================================
  //  链路⑤ 客户端 → 云端HTTP（数据上报）
  // ================================================================

  var linkHttpUpload = {
    id: 'wkwx_link_http_upload',
    name: '⑤ 客户端 → 云端HTTP（数据上报）',
    direction: 'upstream-http',
    color: '#ce93d8',
    description: '客户端通过 HTTP 接口将企微批量数据（标签信息、群列表、群成员详情、服务免打扰等）上报到云端 qun-center 服务，使用企微专属 API 端点',
    mermaid: [
      'graph TD',
      '    s0["业务触发<br/>convert-service/workwx"]',
      '    s1["数据组装<br/>wkUserListResponseMsgHandler等"]',
      '    s2["HTTP请求<br/>httpFetch"]',
      '    s3["云端API<br/>qun-center.umeng100.com"]',
      '    s0 -->|"事件驱动触发"| s1',
      '    s1 -->|"构造POST请求"| s2',
      '    s2 -->|"HTTP POST"| s3',
    ].join('\n'),
    ascii: [
      '  convert-service/workwx → wkUserListResponseMsgHandler / wkRomMemberInfoPoolManager',
      '  → httpFetch() → qun-center.umeng100.com (企微专属端点)',
    ].join('\n'),
    nodes: [
      {
        name: '业务触发（企微 convert-service）',
        icon: 'handler',
        file: 'src/msg-center/business/convert-service/workwx/*.js\nsrc/msg-center/dispatch-center/handle/wkUserListResponseMsgHandler.js',
        func: '各企微 convert-service 的 operate() 中触发',
        summary: '在处理企微逆向回报时触发 HTTP 数据上报，由具体业务场景驱动',
        arrow: 'httpFetch()',
        detail: [
          '【5 个企微 HTTP 上报场景】',
          '',
          '① 标签信息上报 → wkTagInfosUrl',
          '  触发: wkUserListResponseMsgHandler.reportLabelInfo()',
          '  触发: workWxGetContactLabelListTaskResponseService.operate()',
          '  文件: wkUserListResponseMsgHandler.js L113-146',
          '  文件: convert-response/workwx/workWxGetContactLabelListTaskResponseService.js',
          '',
          '② 群列表上报 → uploadChatroomListUrl',
          '  触发: wkUserListResponseMsgHandler.reportUploadChatroomList()',
          '  文件: wkUserListResponseMsgHandler.js L520-534',
          '',
          '③ 群成员列表上报 → uploadChatroomMembersUrl',
          '  触发: wkUserListResponseMsgHandler.reportUpdateRoomInfo()',
          '  触发: workWxConversationRefreshService 群成员增量变更',
          '  文件: wkUserListResponseMsgHandler.js L536-564',
          '',
          '④ 企微群成员详情上报 → uploadRoomMemberInfosUrl',
          '  触发: wkRomMemberInfoPoolManager.run()',
          '  触发: uploadRoomMemberInfos.run()',
          '  文件: convert-service/workwx/uploadRoomMemberInfos.js',
          '',
          '⑤ 服务免打扰信息 → fwUsersUrl',
          '  触发: workWxGetFwUserService.operate()',
          '  文件: convert-service/workwx/workWxGetFwUserService.js L60-81',
        ].join('\n'),
        dataIn: '企微业务数据（标签/群/成员）',
        dataOut: '构造的 HTTP 请求参数',
        logKeywords: ['reportLabelInfo', 'reportUploadChatroomList', 'reportUpdateRoomInfo'],
      },
      {
        name: '数据组装与发送',
        icon: 'process',
        file: 'src/msg-center/common/fetch.js',
        func: 'httpFetch(url, options)',
        summary: '使用 node-fetch 封装的 HTTP 工具发送 POST 请求',
        arrow: '云端API',
        detail: [
          '【企微专属 HTTP 端点 applicationProd.js】',
          '',
          'wkTagInfosUrl:',
          '  http://qun-center.umeng100.com/window/task/wkTagInfos',
          '  用途: 企微标签信息上报',
          '',
          'fwUsersUrl:',
          '  http://qun-center.umeng100.com/window/task/updateServiceAccountSubscribe',
          '  用途: 服务免打扰信息上报',
          '',
          'uploadChatroomListUrl:',
          '  http://qun-center.umeng100.com/window/task/updateChatroomList',
          '  用途: 企微群列表上报',
          '',
          'uploadChatroomMembersUrl:',
          '  http://qun-center.umeng100.com/window/task/updateChatroomInfo',
          '  用途: 企微群成员列表上报',
          '',
          'uploadRoomMemberInfosUrl:',
          '  http://qun-center.umeng100.com/window/task/updateWkChatroomMemberInfos',
          '  用途: 企微群成员详情上报（含内部/外部联系人区分）',
        ].join('\n'),
        dataIn: 'HTTP 请求参数 (url, method, body)',
        dataOut: 'HTTP 响应 (JSON)',
        logKeywords: ['httpFetch', 'wkTagInfos', 'updateChatroomList', 'updateWkChatroomMemberInfos'],
      },
      {
        name: '云端API (qun-center)',
        icon: 'cloud',
        file: '云端服务: qun-center.umeng100.com',
        func: 'REST API',
        summary: '接收企微客户端上报的数据（标签/群/成员/服务号），存储到云端数据库',
        arrow: '',
        detail: [
          '生产: qun-center.umeng100.com',
          '测试: test-qun-center.umeng100.com',
        ].join('\n'),
        dataIn: 'HTTP POST 请求',
        dataOut: 'HTTP 响应 { code, msg, data }',
        logKeywords: [],
      },
    ],
  };

  window.WKWX.linkFrontPush = linkFrontPush;
  window.WKWX.linkFrontDown = linkFrontDown;
  window.WKWX.linkHttpUpload = linkHttpUpload;
})();
