/**
 * 企业微信数据链路 — 链路①② (下行任务 + 上行回报)
 */
(function () {
  'use strict';

  window.WKWX = window.WKWX || {};

  // ================================================================
  //  链路① 云端MQTT → 客户端 → 逆向（下行任务）
  // ================================================================

  var linkDownstream = {
    id: 'wkwx_link_downstream',
    name: '① 云端MQTT → 客户端 → 逆向（下行任务）',
    direction: 'downstream',
    color: '#4fc3f7',
    description: '云端通过 MQTT 下发任务，客户端按 registry.workWx 判断走企微处理器列表 WorkWxConvertServiceList（25个），经入站分发通过 IPC 管道发送到 WXWork.exe 进程执行',
    mermaid: [
      'graph TD',
      '    sc["MQTT连接建立<br/>mqttHelper.js"]',
      '    sr["MQTT消息接收<br/>mqttClientBase.js"]',
      '    st["任务路由分发<br/>runTask - workWx分支"]',
      '    sh["task-mqtt/wkwx 处理器<br/>WorkWxConvertServiceList 25个"]',
      '    so["operate 业务逻辑<br/>task-mqtt/wkwx/具体任务.js"]',
      '    si["云端入站标记<br/>cloudFlowInBound.js"]',
      '    sd["入站分发处理<br/>dispatchInBound.js"]',
      '    ss["IPC发送到逆向<br/>reverseSend.js"]',
      '    sw["企业微信进程<br/>WXWork.exe"]',
      '    sc -->|"登录/重连触发"| sr',
      '    sr -->|"JSON解析/去重/过期检查"| st',
      '    st -->|"registry.workWx=true"| sh',
      '    sh -->|"filter匹配 → operate"| so',
      '    so -->|"cloudFlowInBound"| si',
      '    si -->|"flowSource=CLOUD"| sd',
      '    sd -->|"typeConvert+加锁"| ss',
      '    ss -->|"IPC管道"| sw',
    ].join('\n'),
    ascii: [
      '  [MQTT连接建立] → [MQTT消息接收] → runTask(registry.workWx=true)',
      '  → WorkWxConvertServiceList.filter() → operate() → cloudFlowInBound.js',
      '  → dispatchInBound.js(typeConvert) → reverseSend.js → [IPC管道] → WXWork.exe',
    ].join('\n'),
    nodes: [
      {
        name: 'MQTT连接建立',
        icon: 'cloud',
        file: 'src/msg-center/core/mq/mqttHelper.js\nsrc/msg-center/core/mq/mqttClientBase.js',
        func: 'connectMqtt({ wxId }) → initMqttClient()',
        summary: '建立与云端 MQTT Broker 的连接，订阅任务 Topic。企微与个微共用同一套连接机制，由 loginService/PingTimer 触发。',
        arrow: 'onMessage 事件',
        detail: [
          '【与个微差异】',
          '企微和个微共用同一套 MQTT 连接代码，区别在于 registry 对象中 workWx=true',
          '',
          '【触发来源】',
          '① loginService.js — 登录成功后建立连接',
          '② PingTimer.js — 心跳发现断连后自动重连（30秒限流）',
        ].join('\n'),
        dataIn: '{ wxId }',
        dataOut: 'registry.mqttClient（已建立的 MQTT 客户端实例）',
        logKeywords: ['mqttClientBase:mqtt init', 'handleConnect'],
      },
      {
        name: 'MQTT消息接收',
        icon: 'cloud-download',
        file: 'src/msg-center/core/mq/mqttClientBase.js',
        func: 'client.on("message", callback) → execute()',
        lines: '349-434',
        summary: '接收云端 MQTT 消息，JSON解析/去重/过期检查，调用 execute() → runTask()',
        arrow: 'execute() → runTask()',
        detail: [
          '1. replaceLargeNumbers — 17位以上数字转字符串',
          '2. JSON.parse — 解析为 ServerTaskBO',
          '3. 过期检查: createTime 超过3小时则丢弃',
          '4. 去重: mqttTaskMapLock 以 receiveId 去重',
          '5. type===100（群发）走 executeWithDelay；其他随机延迟 0~1秒',
        ].join('\n'),
        dataIn: 'Buffer (MQTT payload)',
        dataOut: 'ServerTaskBO { taskId, type, wxId, createTime, content }',
        logKeywords: ['MqttClientUtil', '收到MQTT消息', 'taskId'],
      },
      {
        name: '任务路由分发（企微分支）',
        icon: 'router',
        file: 'src/msg-center/core/mq/mqttClientBase.js',
        func: 'runTask(wxId, serverTaskBO, registry)',
        lines: '361-376',
        summary: '判断 registry.workWx → 遍历 WorkWxConvertServiceList（25个企微处理器），按 filter() 匹配',
        arrow: 'filter() → operate()',
        detail: [
          '【核心分支逻辑 L361-376】',
          'if (registry.workWx) {',
          '    for (WorkWxConvertServiceList) {',
          '        if (service.filter(serverTaskBO)) {',
          '            service.operate(serverTaskBO, wxId);',
          '        }',
          '    }',
          '} else { // 个微分支走 WxConvertServiceList }',
          '',
          '【WorkWxConvertServiceList 注册位置】',
          'mqttClientBase.js L55-80，共 25 个企微处理器',
        ].join('\n'),
        dataIn: 'ServerTaskBO { taskId, type, wxId, content }',
        dataOut: '路由到 task-mqtt/wkwx/ 下对应处理器',
        logKeywords: ['runTask', 'filter'],
      },
      {
        name: 'task-mqtt/wkwx 处理器（25个）',
        icon: 'handler',
        file: 'src/msg-center/business/task-mqtt/wkwx/*.js',
        func: 'filter(serverTaskBO) + operate(serverTaskBO, wxId)',
        summary: 'WorkWxConvertServiceList 共 25 个处理器，由 filter() 按 type 匹配，匹配后执行 operate() 业务逻辑',
        arrow: 'operate() → cloudFlowInBound()',
        detail: [
          '【25个处理器完整清单见下方 MQTT 任务类型清单】',
          '',
          '【filter 匹配规则】',
          '每个处理器的 filter() 检查 serverTask.type 是否等于特定常量',
          '例: mqttWorkWxChatService.filter() 匹配 type==1 或 type==100',
          '',
          '【operate 通用模式】',
          '1. 校验参数（toUsernames/chatroom/content 等）',
          '2. 构建企微专用 BO 对象（设置 GalaxyTaskType）',
          '3. 媒体类型需下载文件到本地',
          '4. 调用 cloudFlowInBound(null, wxId, JSON.stringify(task))',
        ].join('\n'),
        dataIn: 'ServerTaskBO { taskId, type, content }',
        dataOut: 'cloudFlowInBound() 进入入站分发',
        logKeywords: ['mqttWork', 'operate', 'cloudFlowInBound'],
      },
      {
        name: '云端入站标记',
        icon: 'tag',
        file: 'src/msg-center/dispatch-center/dispatch/cloudFlowInBound.js',
        func: 'cloudFlowInBound(channelId, wxId, message)',
        summary: '在消息中标记 flowSource=CLOUD(2)，进入公共入站分发链路',
        arrow: 'dispatchInBound()',
        detail: [
          '1. 添加 FLOW_SOURCE_KEY = CLOUND(2)',
          '2. 传递 channelId/wxId/message 给 dispatchInBound',
          '3. flowSource=2 决定上行时路由到云端出站',
        ].join('\n'),
        dataIn: 'ClientTask JSON string',
        dataOut: '附加 flowSource=2 的 ClientTask',
        logKeywords: ['cloudFlowInBound', 'CLOUND'],
      },
      {
        name: '入站分发处理（含企微类型转换）',
        icon: 'dispatch',
        file: 'src/msg-center/dispatch-center/dispatchInBound.js',
        func: 'dispatchInBound() → typeConvert() → processInBoundTask()',
        summary: '校验 registry，typeConvert 将 sendmsg_* 统一为 sendmsg_，匹配 WkTaskCallBack 回调映射，加锁后发到逆向',
        arrow: 'reverseSend.sendMessage()',
        detail: [
          '【企微关键差异: typeConvert L17-23】',
          'function typeConvert(type) {',
          '    if (type.startsWith("sendmsg_")) typeTemp = "sendmsg_";',
          '    return typeTemp;',
          '}',
          '所有 sendmsg_sendtext/sendmsg_sendimage 等统一转为 sendmsg_',
          '',
          '【WkTaskCallBack 回调映射 wkTaskCallback.js】',
          'taskCallbackMap = {',
          '  "sendmsg_": {',
          '    firstCallbackType: "recvmsg",',
          '    secondCallbackType: "sendmsg_",',
          '    thirdCallbackType: "msgreport"',
          '  }',
          '}',
          '',
          '【processInBoundTask 流程】',
          '1. 检查 WkTaskCallBack.taskCallbackMap[type]',
          '2. workWxFlag=true → 使用企微回调映射',
          '3. 创建 galaxyTaskStatus 写入 GalaxyTaskCache',
          '4. 调用 inBoundAct() → reverseSend.sendMessage()',
        ].join('\n'),
        dataIn: 'ClientTask JSON (含 flowSource)',
        dataOut: '发送到 reverseSend 的 message',
        logKeywords: ['dispatchInBound', 'typeConvert', 'processInBoundTask'],
      },
      {
        name: 'IPC发送到逆向',
        icon: 'send',
        file: 'src/msg-center/dispatch-center/reverseSend.js',
        func: 'sendMessage() → pipeLineSend()',
        summary: '通过 IPC 命名管道将任务发送到 WXWork.exe 进程',
        arrow: 'IPC管道',
        detail: [
          '1. 按 wxId/channelId 查找 registry',
          '2. 重复过滤: lockKey = ${wxid}-${taskId}-${type}',
          '3. pipeLineSend(): Clibrary.IpcClientSendMessage(pipeCode, message)',
          '4. 加锁: taskLock 5秒后自动删除',
        ].join('\n'),
        dataIn: 'JSON string message',
        dataOut: '通过 PipeCore.dll 发送的二进制数据',
        logKeywords: ['pipeLineSend', 'IpcClientSendMessage', 'reverseSend'],
      },
      {
        name: '企业微信进程（WXWork.exe）',
        icon: 'wechat',
        file: '逆向端 (WXWork.exe IPC)',
        func: '由企业微信进程内部处理',
        summary: '企业微信进程通过 IPC 管道接收指令并执行操作（发消息、改群名、踢人等）',
        arrow: '',
        detail: [
          '【与个微差异】',
          '进程名: WXWork.exe（个微为 weixin.exe）',
          'IPC管道: 相同的 PipeCore.dll 通信机制',
          '指令格式: 使用企微专用 GalaxyTaskType（如 sendmsg_sendtext）',
          '',
          '【进程识别 ipcUtil.js】',
          'tasklist /fi "imagename eq WXWork.exe"',
          'processMap[pid] = true  // 标记为企微',
        ].join('\n'),
        dataIn: 'IPC 指令 (JSON)',
        dataOut: '操作执行结果',
        logKeywords: [],
      },
    ],
  };

  // ================================================================
  //  链路② 逆向 → 客户端 → 云端MQTT（上行回报）
  // ================================================================

  var linkUpstream = {
    id: 'wkwx_link_upstream',
    name: '② 逆向 → 客户端 → 云端MQTT（上行回报）',
    direction: 'upstream',
    color: '#81c784',
    description: '企微进程执行结果通过 IPC 回传，经 WkMsgHandlerCenter 两段式回执匹配后，由 WorkWxConvertServiceList（40+处理器）转换格式并 MQTT 上报云端',
    mermaid: [
      'graph TD',
      '    s0["企微进程 WXWork.exe<br/>IPC回报"]',
      '    s1["IPC轮询接收<br/>asyncSelectTask.js"]',
      '    s2["出站分发<br/>dispatchOutBound.js"]',
      '    s3["企微消息处理中心<br/>workWxMsgHandle.js"]',
      '    s4["业务路由<br/>businessHandler"]',
      '    s5["云端出站处理<br/>cloudFlowOutBound.js"]',
      '    s6["convert-service/workwx<br/>+ convert-response/workwx"]',
      '    s7["MQTT上报云端<br/>mqttSend.js"]',
      '    s0 -->|"IPC管道"| s1',
      '    s1 -->|"200ms轮询"| s2',
      '    s2 -->|"workWx=true → WkMsgHandlerCenter"| s3',
      '    s3 -->|"两段式回执匹配"| s4',
      '    s4 -->|"flowSource=CLOUD"| s5',
      '    s5 -->|"WorkWxConvertServiceList filter"| s6',
      '    s6 -->|"构造ClientMsg"| s7',
    ].join('\n'),
    ascii: [
      '  WXWork.exe → [IPC管道] → asyncSelectTask.js → dispatchOutBound.js',
      '  → WkMsgHandlerCenter(两段式回执) → businessHandler → cloudFlowOutBound.js',
      '  → convert-service/workwx/*.js + convert-response/workwx/*.js → mqttSend.js',
    ].join('\n'),
    nodes: [
      {
        name: '企微进程回报（WXWork.exe）',
        icon: 'wechat',
        file: '逆向端 (WXWork.exe IPC)',
        func: '企业微信进程产生消息/回报',
        summary: '企微进程在任务执行完毕或收到被动事件时，通过 IPC 管道回传结果',
        arrow: 'IPC管道',
        detail: [
          '回报场景:',
          '- 消息发送结果: sendmsg_sendtext / sendmsg_sendimage 等',
          '- 被动事件: recvmsg（收到消息）、NotifyMessage（好友申请）',
          '- 群变更: RefreshConversations、UpdateConversationInfo',
          '- 文件传输: filepath',
          '- 回执确认: msgreport',
        ].join('\n'),
        dataIn: '企微内部事件',
        dataOut: 'IPC 消息 (JSON)',
        logKeywords: [],
      },
      {
        name: 'IPC轮询接收',
        icon: 'receive',
        file: 'src/msg-center/core/reverse/asyncSelectTask.js',
        func: 'run() → loop() → successIpcConnect()',
        summary: '200ms轮询 IPC 管道，接收企微进程回传的消息',
        arrow: 'dispatchOutBound()',
        detail: [
          '1. loop() 递归: IpcSelectCltChannel(pipeCode)',
          '   selectCode==0: 无数据 → sleep(200ms)',
          '   selectCode<0: 通道关闭 → 退出',
          '   selectCode>0: 有数据 → successIpcConnect()',
          '2. successIpcConnect():',
          '   IpcClientRecvMessage(pipeCode, selectCode, wxid)',
          '   replaceLargeNumbers(message)',
          '   dispatchOutBound(message, pipeLineWrapper)',
        ].join('\n'),
        dataIn: 'IPC 管道二进制数据',
        dataOut: 'JSON string message',
        logKeywords: ['asyncSelectTask', 'successIpcConnect'],
      },
      {
        name: '出站分发（企微路由）',
        icon: 'dispatch',
        file: 'src/msg-center/dispatch-center/dispatchOutBound.js',
        func: 'dispatchOutBound(message, pipeLineWrapper)',
        lines: '39-52',
        summary: '判断 pipeLineWrapper.workWx → 路由到 WkMsgHandlerCenter（企微消息处理中心）',
        arrow: 'WkMsgHandlerCenter.outBoundMsg()',
        detail: [
          '【核心路由逻辑 L39-52】',
          'if (pipeLineWrapper.workWx) {',
          '    WkMsgHandlerCenter.outBoundMsg(jsonObject, pipeLineWrapper, sendType);',
          '} else {',
          '    WxMsgHandlerCenter.outBoundMsg(jsonObject, pipeLineWrapper, sendType);',
          '}',
          '',
          '【前置处理】',
          '1. JSON.parse(message) 解析',
          '2. 过滤 pong 类型日志',
          '3. bugreport/error 类型上报崩溃',
          '4. 更新 GalaxyVersionCache.galaxyVersion',
        ].join('\n'),
        dataIn: 'JSON string (逆向回报)',
        dataOut: '路由到 WkMsgHandlerCenter',
        logKeywords: ['dispatchOutBound', 'outBoundMsg'],
      },
      {
        name: '企微消息处理中心（两段式回执）',
        icon: 'process',
        file: 'src/msg-center/dispatch-center/handle/workWxMsgHandle.js\nsrc/msg-center/dispatch-center/handle/msgHandleBase.js',
        func: 'WkMsgHandlerCenter.outBoundMsg() → messageHandler()',
        summary: '企微两段式回执: 第一段 recvmsg/sendmsg_* → 第二段 sendmsg_*/recvmsg → 第三段 msgreport，匹配后路由到业务处理',
        arrow: 'businessHandler()',
        detail: [
          '【企微回执与个微差异 workWxMsgHandle.js】',
          '',
          'isReset(sendType, node):',
          '  node.first 存在且 sendType 为 recvmsg → 重置（企微 recvmsg 表示前一消息已结束）',
          '',
          'isNotContains(sendType):',
          '  仅处理: recvmsg / msgreport / sendmsg_* 开头的 type',
          '  其他类型直接跳过两段式，走直通路径',
          '',
          'isFirstMsg(node, sendType):',
          '  无 node 且 type 为 recvmsg 或 sendmsg_* 前缀',
          '',
          'isSecondMsg(node, sendType):',
          '  有 first、无 second，且 type 为 sendmsg_* 或 recvmsg',
          '',
          'isThirdMsg(node, sendType):',
          '  有 first 和 second，且 type 为 msgreport',
          '',
          '【关联key生成 msgHandleBase.js L1279】',
          '企微: key = this.getQywxKey(jsonObj, wxId)',
          '个微: key = this.getWx4AssociationKey(jsonObj, wxId)',
          '',
          '【responseMsgHandler 分支 L1501-1519】',
          'wrapper.workWx → WkUserListResponseMsgHandler',
          '!wrapper.workWx → wxUserListResponseMsgHandler',
        ].join('\n'),
        dataIn: '逆向回报 JSON { type, toUser, timer, ... }',
        dataOut: '完整的 MsgResNode { first, second, third }',
        logKeywords: ['messageHandler', 'MsgResNode', 'thirdMsgHandler'],
      },
      {
        name: '业务路由（按来源分发）',
        icon: 'router',
        file: 'src/msg-center/dispatch-center/handle/msgHandleBase.js',
        func: 'businessHandler(msgResNode, key, pipeLineWrapper)',
        summary: '根据 flowSource 路由: CLOUD(2)→cloudFlowOutBound / FRONT(1)→frontFlowOutBound',
        arrow: 'cloudFlowOutBound()',
        detail: [
          'FLOW_HANDLER_MAP = {',
          '  FRONT(1): frontFlowOutBound,',
          '  CLOUND(2): cloudFlowOutBound,',
          '}',
          '企微MQTT下发任务→flowSource=2→cloudFlowOutBound→上报云端',
        ].join('\n'),
        dataIn: 'MsgResNode + flowSource',
        dataOut: '路由到 cloudFlowOutBound',
        logKeywords: ['businessHandler', 'flowSource'],
      },
      {
        name: '云端出站处理（企微分支）',
        icon: 'cloud-upload',
        file: 'src/msg-center/dispatch-center/dispatch/cloudFlowOutBound.js',
        func: 'cloudFlowOutBound(message, pipeLineWrapper)',
        lines: '232-267',
        summary: '判断 workWx → 遍历 WorkWxConvertServiceList（40+处理器），按 filter 匹配执行 operate',
        arrow: 'filter() → operate()',
        detail: [
          '【核心路由逻辑 L238-249】',
          'if (pipeLineWrapper.workWx) {',
          '    for (WorkWxConvertServiceList) {',
          '        if (service.filter(clientRecord)) {',
          '            service.operate(message, pipeLineWrapper);',
          '        }',
          '    }',
          '} // else → WxConvertServiceList',
          '',
          '【WorkWxConvertServiceList 注册 L189-230】',
          '包含 3 类处理器:',
          '① commonConvertServiceList: LoginService, LogoutService, PongService',
          '② convert-service/workwx/*: 16 个被动事件处理器',
          '③ convert-response/workwx/*: 21 个任务结果处理器',
          '+ convert-taskreport/workwx/*: 任务上报处理器',
          '',
          '【完整处理器清单见下方「上行消息处理器清单」】',
        ].join('\n'),
        dataIn: '逆向回报消息',
        dataOut: '转换后的云端消息格式',
        logKeywords: ['CloudFlowHandler', 'convert-service', 'convert-response'],
      },
      {
        name: 'MQTT上报云端',
        icon: 'cloud-upload',
        file: 'src/msg-center/dispatch-center/mqttSend.js → src/msg-center/core/mq/mqExcuteMsg.js',
        func: 'sendMessage() → mqExcuteMsg()',
        summary: '将处理结果通过 MQTT publish 上报到云端',
        arrow: '',
        detail: [
          '1. mqttSend.sendMessage(wxid, clientMsg):',
          '   填充 clientMsgSource、username、clientVersion',
          '2. mqExcuteMsg(wxid, topic, clientMsg):',
          '   Topic: ApplicationEnv["parentTopic"]',
          '   正常: registry.mqttClient.publish(topic, Buffer)',
          '   异常: UploadMetricTask.run(wxId, Metric.MQTT_SEND_TIMEOUT)',
        ].join('\n'),
        dataIn: 'ClientMsg 对象',
        dataOut: 'MQTT publish payload (JSON Buffer)',
        logKeywords: ['MqttClientUtil-send', '上报MQTT', 'mqExcuteMsg'],
      },
    ],
  };

  window.WKWX.linkDownstream = linkDownstream;
  window.WKWX.linkUpstream = linkUpstream;
})();
