/**
 * Galaxy Client 数据链路分析 - 基础设施节点 & 辅助函数
 * 依赖：无（第一个加载）
 * 导出：window._GCData.INFRA / clone / buildDownstreamFlow / buildUpstreamFlow / buildEventUpstreamFlow
 */
(function () {
  'use strict';

  window._GCData = {};

  const INFRA = {
    // ---------- 下行链路共享节点 ----------
    mqttRecv: {
      id: 'mqtt_recv',
      name: 'MQTT消息接收',
      icon: 'cloud-download',
      file: 'src/msg-center/core/mq/mqttClientBase.js',
      func: 'client.on("message", callback)',
      lines: '349-434',
      summary: '接收云端MQTT消息，JSON解析，过期检查，去重',
      arrow: 'execute() → runTask()',
      detail: [
        '1. replaceLargeNumbers(message.toString("utf8")) — 将17位以上数字转为字符串，防止JS精度丢失',
        '2. JSON.parse(messageUtf8) — 解析为 dataInfo 对象',
        '3. 过期检查: 若 createTime 距今超过配置时间（默认3小时）则丢弃',
        '4. 去重: 使用 mqttTaskMapLock 以 taskId 为 key，防止重复处理',
        '5. type===100（群发）走延迟队列 executeWithDelay()；其他随机延迟 0~1秒后执行',
      ].join('\n'),
      dataIn: 'Buffer (MQTT payload)',
      dataOut: 'ServerTaskBO { taskId, type, wxId, createTime, content, ... }',
      logKeywords: ['MqttClientUtil', 'taskId', '收到MQTT消息'],
      logQuery: '在 SLS 搜索: taskId=<任务ID> 或 wxid_xxx',
      cacheOps: 'mqttTaskMapLock.set(taskId, true) — 去重锁，超时自动删除',
      dbOps: '',
    },

    mqttRoute: {
      id: 'mqtt_route',
      name: '任务路由分发',
      icon: 'router',
      file: 'src/msg-center/core/mq/mqttClientBase.js',
      func: 'runTask(wxId, serverTaskBO, registry)',
      lines: '458-478',
      summary: '遍历处理器列表，按 filter() 匹配对应处理器。[微信] WxConvertServiceList（16个）/ [企微] WorkWxConvertServiceList（25个）',
      arrow: 'filter() → operate()',
      detail: [
        '1. 判断 registry.workWx → 选择对应平台处理器列表',
        '   [微信] workWx=false → WxConvertServiceList（16个处理器）',
        '   [企微] workWx=true  → WorkWxConvertServiceList（25个处理器）',
        '2. 遍历对应列表，对每个 service 调用 filter(serverTaskBO)',
        '3. filter 返回 true 的执行 operate()',
        '4. 同一任务可能被多个 service 处理（取决于 filter 实现）',
      ].join('\n'),
      dataIn: 'ServerTaskBO { taskId, type, wxId, content }',
      dataOut: '路由到对应的 task-mqtt handler',
      logKeywords: ['runTask', 'filter'],
      logQuery: '按 taskId 和 type 组合搜索',
      cacheOps: '',
      dbOps: '',
    },

    cloudFlowIn: {
      id: 'cloud_flow_in',
      name: '云端入站标记',
      icon: 'tag',
      file: 'src/msg-center/dispatch-center/dispatch/cloudFlowInBound.js',
      func: 'cloudFlowInBound(channelId, wxId, message)',
      lines: '',
      summary: '由各 task-mqtt 处理器的 operate() 末尾统一调用，标记消息来源为云端（flowSource=2），进入公共入站分发链路',
      arrow: 'dispatchInBound()',
      detail: [
        '【调用来源】',
        '由各 task-mqtt 处理器的 operate() 末尾统一调用，是业务逻辑完成后进入公共链路的统一入口',
        '',
        '【处理逻辑】',
        '1. 在消息中添加 FLOW_SOURCE_KEY = CLOUND(2)，标识来源为云端',
        '2. 传递 channelId、wxId、message 给 dispatchInBound',
        '3. flowSource=2 决定了上行回报时路由到云端出站（而非前端推送）',
      ].join('\n'),
      dataIn: 'ClientTask JSON string',
      dataOut: '附加 flowSource=2 的 ClientTask',
      logKeywords: ['cloudFlowInBound', 'CLOUND'],
      logQuery: '搜索 flowSource 或 cloudFlowInBound',
      cacheOps: '',
      dbOps: '',
    },

    dispatchIn: {
      id: 'dispatch_in',
      name: '入站分发处理',
      icon: 'dispatch',
      file: 'src/msg-center/dispatch-center/dispatchInBound.js',
      func: 'dispatchInBound() → processInBoundTask() → inBoundAct()',
      lines: '',
      summary: '校验、类型转换、任务缓存、加锁，最终调用 reverseSend 发送到逆向',
      arrow: 'reverseSend.sendMessage()',
      detail: [
        '1. 校验 registry 是否存在（逆向进程是否连接）',
        '2. JSON.parse 解析消息',
        '3. typeConvert(type) — 企业微信发送类型统一转换（个微4.0此步骤无影响）',
        '4. 发送类任务: 加锁、构建 galaxyTaskStatus、写入 GalaxyTaskCache',
        '5. 调用 inBoundAct() → reverseSendService.sendMessage()',
      ].join('\n'),
      dataIn: 'ClientTask JSON (含 flowSource)',
      dataOut: '发送到 reverseSend 的 message',
      logKeywords: ['dispatchInBound', 'processInBoundTask', 'inBoundAct'],
      logQuery: '搜索 dispatchInBound + wxid',
      cacheOps: 'GalaxyTaskCache.GALAXY_TASK_STATUS_MAP — 任务状态缓存（三段式/两段式回执用）',
      dbOps: '',
    },

    reverseSend: {
      id: 'reverse_send',
      name: 'IPC发送到逆向',
      icon: 'send',
      file: 'src/msg-center/dispatch-center/reverseSend.js',
      func: 'sendMessage() → pipeLineSend()',
      lines: '',
      summary: '通过 IPC 命名管道将任务发送到逆向进程（[微信] weixin.exe / [企微] WXWork.exe）',
      arrow: 'IPC管道',
      detail: [
        '1. 按 wxId/channelId 查找 registry',
        '2. 重复过滤: lockKey = ${wxid}-${taskId}-${type}，已存在则跳过',
        '3. pipeLineSend(): 调用 Clibrary.IpcClientSendMessage(pipeCode, message)',
        '4. 加锁: taskLock.set(lockKey, true)，5秒后自动 delete',
      ].join('\n'),
      dataIn: 'JSON string message',
      dataOut: '通过 PipeCore.dll 发送的二进制数据',
      logKeywords: ['pipeLineSend', 'IpcClientSendMessage', 'reverseSend'],
      logQuery: '搜索 reverseSend + wxid',
      cacheOps: 'taskLock — 5秒内防重复发送',
      dbOps: '',
    },

    wechatDown: {
      id: 'wechat_process_down',
      name: '逆向进程接收',
      icon: 'wechat',
      file: '逆向端 (PipeCore.dll IPC)',
      func: '由逆向进程内部处理',
      lines: '',
      summary: '逆向进程（[微信] weixin.exe / [企微] WXWork.exe）通过 IPC 管道接收指令并执行对应操作',
      arrow: '',
      detail: [
        '逆向进程通过 PipeCore.dll 建立的命名管道接收客户端指令',
        '[微信] weixin.exe / [企微] WXWork.exe 根据指令 type 字段执行对应操作',
        '操作完成后通过相同管道回报结果',
      ].join('\n'),
      dataIn: 'IPC 指令 (JSON)',
      dataOut: '操作执行结果',
      logKeywords: [],
      logQuery: '逆向端日志需在逆向进程侧查看',
      cacheOps: '',
      dbOps: '',
    },

    // ---------- 上行链路共享节点 ----------
    wechatUp: {
      id: 'wechat_process_up',
      name: '逆向进程回报',
      icon: 'wechat',
      file: '逆向端 (PipeCore.dll IPC)',
      func: '逆向进程产生消息/回报',
      lines: '',
      summary: '逆向进程（[微信] weixin.exe / [企微] WXWork.exe）产生事件或任务执行结果，通过 IPC 管道回传',
      arrow: 'IPC管道',
      detail: [
        '逆向进程在以下情况产生消息：',
        '- 任务执行完毕的回报（如消息发送成功/失败）',
        '- 被动事件（如收到新消息、好友请求、群成员变更等）',
        '- 系统事件（如登录状态变化）',
      ].join('\n'),
      dataIn: '逆向进程内部事件',
      dataOut: 'IPC 消息 (JSON)',
      logKeywords: [],
      logQuery: '逆向端日志需在逆向进程侧查看',
      cacheOps: '',
      dbOps: '',
    },

    ipcPoll: {
      id: 'ipc_poll',
      name: 'IPC轮询接收',
      icon: 'receive',
      file: 'src/msg-center/core/reverse/asyncSelectTask.js',
      func: 'run() → loop() → successIpcConnect()',
      lines: '',
      summary: '200ms轮询 IPC 管道，接收逆向端回传的消息',
      arrow: 'dispatchOutBound()',
      detail: [
        '1. loop() 递归循环：',
        '   - selectCode = Clibrary.IpcSelectCltChannel(pipeCode)',
        '   - selectCode == 0: 无数据 → sleep(200ms) → 继续轮询',
        '   - selectCode < 0: 通道关闭 → closeIpcConnect() → 退出',
        '   - selectCode > 0: 有数据 → successIpcConnect()',
        '2. successIpcConnect():',
        '   - Clibrary.IpcClientRecvMessage(pipeCode, selectCode, wxid) 读取',
        '   - replaceLargeNumbers(message) 处理大数字',
        '   - dispatchOutBound(message, wrapper) 分发到业务层',
      ].join('\n'),
      dataIn: 'IPC 管道二进制数据',
      dataOut: 'JSON string message',
      logKeywords: ['asyncSelectTask', 'IpcSelectCltChannel', 'successIpcConnect'],
      logQuery: '搜索 asyncSelectTask 或 IpcClientRecvMessage',
      cacheOps: '',
      dbOps: '',
    },

    dispatchOut: {
      id: 'dispatch_out',
      name: '出站分发',
      icon: 'dispatch',
      file: 'src/msg-center/dispatch-center/dispatchOutBound.js',
      func: 'dispatchOutBound(message, pipeLineWrapper)',
      lines: '',
      summary: '解析逆向消息，按进程类型路由到对应消息处理中心。[微信] WxMsgHandlerCenter / [企微] WkMsgHandlerCenter',
      arrow: 'MsgHandlerCenter.outBoundMsg()',
      detail: [
        '1. JSON.parse(message) 解析消息（空消息用 {} 兜底）',
        '2. 过滤 pong 心跳消息（不写日志）',
        '3. bugreport → reportLog(REVERSE_BUG_REPORT)',
        '4. type 含 "error"（排除 cdnonerror）→ reportLog(REVERSE_ERROR)',
        '5. 更新 GalaxyVersionCache.galaxyVersion（版本号变化时）',
        '6. 按 pipeLineWrapper.workWx 路由:',
        '   [企微] workWx=true  → WkMsgHandlerCenter.outBoundMsg()',
        '   [微信] workWx=false →',
        '     第三阶段回调(THIRD_CALLBACKS) + status!=0(失败):',
        '       → setTimeout(taskFailWaitTime) 延迟处理，给逆向更多响应时间',
        '     其他情况: → WxMsgHandlerCenter.outBoundMsg()',
      ].join('\n'),
      dataIn: 'JSON string (逆向回报)',
      dataOut: '路由到 WxMsgHandlerCenter / WkMsgHandlerCenter',
      logKeywords: ['dispatchOutBound', 'outBoundMsg'],
      logQuery: '搜索 dispatchOutBound + wxid 或按 type 过滤',
      cacheOps: 'GalaxyVersionCache 更新',
      dbOps: '',
    },

    msgHandle: {
      id: 'msg_handle',
      name: '消息处理中心（回执匹配）',
      icon: 'process',
      file: 'src/msg-center/dispatch-center/handle/msgHandleBase.js\nsrc/msg-center/dispatch-center/handle/wxMsgHandle.js\nsrc/msg-center/dispatch-center/handle/workWxMsgHandle.js',
      func: 'outBoundMsg() → messageHandler() → responseMsgHandler() → businessHandler()',
      lines: 'msgHandleBase.js: 1656行',
      summary: '上行链路核心处理中心。完整调用链：outBoundMsg → messageHandler（5道过滤 + 回执匹配）→ responseMsgHandler（userlist特殊处理）→ businessHandler（按flowSource路由）。[微信] 两段式回执 / [企微] 三段式回执，另有直通路径跳过回执。',
      arrow: 'businessHandler()',
      detail: [
        '══════════════════════════════════════════════════════════',
        '第1层 — 完整调用链',
        '══════════════════════════════════════════════════════════',
        '',
        'outBoundMsg(jsonObj, wrapper, sendType)',
        '  │ notDealSet 过滤（如 AVATAR_CHANGED 直接丢弃）',
        '  ├→ messageHandler(jsonObj, wrapper, sendType)',
        '  │     5道过滤 + 回执匹配（详见第2层、第3层）',
        '  │     返回 jsonObject（可能被修改了 taskId/flowSource/status）',
        '  ├→ responseMsgHandler(jsonObject, type, wrapper)',
        '  │     [微信] wxUserListResponseMsgHandler 处理 userlist/userinfolist',
        '  │     [企微] WkUserListResponseMsgHandler 处理 userlist/room 响应',
        '  │     unknownerror + handle_GetUserList 等 → executeError()',
        '  └→ send() → businessHandler()（详见第4层）',
        '',
        '══════════════════════════════════════════════════════════',
        '第2层 — messageHandler 过滤链（5道过滤，任一命中则 return jsonObj 跳过回执）',
        '══════════════════════════════════════════════════════════',
        '',
        '过滤1: isNotContains(sendType)',
        '  [微信] !CALLBACK_SET.has(sendType)  — CALLBACK_SET 含 sendmessage/recvmsg/msgreport 等',
        '  [企微] 非 recvmsg && 非 msgreport && 非 sendmsg_* 前缀',
        '  → 不在处理范围的消息类型直接跳过回执匹配',
        '',
        '过滤2: isSysMsg(jsonObj)',
        '  to === "newsapp" → 系统新闻消息，跳过',
        '',
        '过滤3: isNotSendMsg(jsonObj)',
        '  type==="recvmsg" && sequence && sequence!==0 → 非普通群发消息，跳过',
        '',
        '过滤4: isNotSelfSendMsg(jsonObj, ownerWxId)  —— 仅[微信]',
        '  type==="recvmsg" && from!==ownerWxId → 不是本人发送的消息，跳过',
        '  （此消息跳过回执但仍会进入 businessHandler → convert-service 处理）',
        '',
        '过滤5: [微信4.0] 媒体类型校验  —— 仅[微信]',
        '  recvmsg + msgtype=49(文件) → 无 attachid 的无效消息过滤',
        '  recvmsg + msgtype=43(视频) → 无 aeskey 的无效消息过滤',
        '',
        '══════════════════════════════════════════════════════════',
        '第3层 — 回执匹配机制（通过过滤后进入）',
        '══════════════════════════════════════════════════════════',
        '',
        '┌─────────────────┬───────────────────────┬───────────────────────┐',
        '│     维度        │  [微信4.0] 两段式      │  [企微] 三段式          │',
        '├─────────────────┼───────────────────────┼───────────────────────┤',
        '│ 第一条(first)   │ sendmessage           │ recvmsg 或 sendmsg_*  │',
        '│ 第二条(second)  │ recvmsg → 直接完成     │ sendmsg_* 或 recvmsg  │',
        '│ 第三条(third)   │ 无需（两段即完成）      │ msgreport             │',
        '│ Key 生成        │ getWx4AssociationKey   │ wxId_clientId         │',
        '│                 │ (from-to-msgType-hash) │                       │',
        '│ 完成判断        │ isWx4RecvmsgComplete   │ isThirdMsg            │',
        '│ status转换      │ status=2→0(成功)       │ 无需转换              │',
        '│                 │ 其他→1(失败)           │                       │',
        '│ flowSource补全  │ recvmsg补充flowSource=2│ 无需补全              │',
        '│ taskId继承      │ recvmsg继承first.taskId│ second继承taskIdMap   │',
        '└─────────────────┴───────────────────────┴───────────────────────┘',
        '',
        '回执匹配流程:',
        '  isFirstMsg  → new MsgResNode { first: getDefaultMsgResNode(jsonObj) }',
        '                → add(node, key) 缓存到 msgResNodeMap',
        '  isSecondMsg → node.second = getDefaultMsgResNode(jsonObj)',
        '                [微信4.0] isWx4RecvmsgComplete() → true → thirdMsgHandler() 完成',
        '                [企微] 继续等待第三条',
        '  isThirdMsg  → node.third = jsonObj → thirdMsgHandler() 完成',
        '  errorOrder  → 以上都不匹配，尝试 taskIdMap/getCacheTaskId 补救',
        '',
        'thirdMsgHandler(msgResNode, key):',
        '  → 从 first/second 获取 taskId',
        '  → 更新 GalaxyTaskCache.GALAXY_TASK_STATUS_MAP 所有阶段为 RECEIVE_STATUS',
        '  → 清理 msgResNodeMap 和 taskMsgTypeMap',
        '  → 返回 third（携带 taskId），交给 businessHandler 路由',
        '',
        '══════════════════════════════════════════════════════════',
        '直通路径（跳过回执匹配，直接路由）',
        '══════════════════════════════════════════════════════════',
        '',
        '[微信4.0] 以下类型无 taskId 时直接添加 flowSource=2 跳过三段式:',
        '  • HandleDelContact         — 删除好友/退群',
        '  • recvmsgs                 — 批量接收消息',
        '  • CreateChatRoomResponse   — 新建群聊响应',
        '  • HandleChatroomMemberResp — 群成员变动',
        '  • AddChatRoomMemberResponse— 邀请加入群聊',
        '  • ModContactRemarkResponse — 备注修改通知',
        '  • recvmsg(status=2 且非任务回执) — 自己发送的消息同步',
        '',
        '[共用] 特殊路由（businessHandler 内直接强制走 cloudFlowOutBound）:',
        '  • type===userlist           — 好友列表响应',
        '  • QUICK_SEND_TYPE.includes(type) — 快速发送类型',
        '',
        '[共用] 无 flowSource 的消息 → outBoundByBroadcast 广播（同时推送前端+云端）',
        '',
        '══════════════════════════════════════════════════════════',
        '数据结构',
        '══════════════════════════════════════════════════════════',
        '',
        'MsgResNode { first, second, third, expireTime, thirdTime }',
        '  first/second/third = { taskId, hash, status, client_id, type }',
        'msgResNodeMap[key] = MsgResNode  （视频消息用数组: MsgResNode[]）',
        'taskIdMap[key] = taskId  （3秒过期，用于 first→second 的 taskId 传递）',
        '过期清理: 10秒轮询 removeExpireNode()，msgResNodeMap 超200条触发告警',
      ].join('\n'),
      dataIn: '逆向回报 JSON (含 type, toUser, timer 等)',
      dataOut: '完整的三段消息 MsgResNode',
      logKeywords: ['messageHandler', 'MsgResNode', 'thirdMsgHandler', 'galaxyTaskStatus'],
      logQuery: '搜索 messageHandler + wxid 或 galaxyTaskStatus + taskId',
      cacheOps: 'msgResNodeMap — 消息节点缓存 (key: wxId_toUser_timer)\nGalaxyTaskCache.GALAXY_TASK_STATUS_MAP — 任务状态',
      dbOps: '',
    },

    businessRoute: {
      id: 'business_route',
      name: '业务路由（按来源分发）',
      icon: 'router',
      file: 'src/msg-center/dispatch-center/handle/msgHandleBase.js',
      func: 'businessHandler(jsonObject, finalMessage, pipeLineWrapper)',
      lines: '1599-1625',
      summary: '根据消息 flowSource 字段路由：CLOUD(2)→cloudFlowOutBound→上报云端，FRONT(1)→frontFlowOutBound→推送前端，无source→广播两者',
      arrow: 'cloudFlowOutBound() / frontFlowOutBound()',
      detail: [
        'FLOW_HANDLER_MAP 定义（第96-101行）:',
        '  FlowSourceEnum.FRONT  (1) → frontFlowOutBound（推送 WebSocket 前端）',
        '  FlowSourceEnum.CLOUND (2) → cloudFlowOutBound（上报云端 MQTT）',
        '',
        'businessHandler 路由逻辑（第1599-1625行）:',
        '',
        '1. 强制走云端:',
        '   type===USER_LIST 或 QUICK_SEND_TYPE → 直接 cloudFlowOutBound',
        '   （不看 flowSource，好友列表和快速发送结果必须上报云端）',
        '',
        '2. 按 flowSource 路由:',
        '   source = jsonObject.flowSource',
        '   source=2(CLOUD) → cloudFlowOutBound（云端MQTT下发的任务回执上报）',
        '   source=1(FRONT) → frontFlowOutBound（前端下发的指令执行结果推送）',
        '   source=3(OWNER) → 也走 FLOW_HANDLER_MAP（同上，但实际无此分支）',
        '',
        '3. 无 flowSource:',
        '   → outBoundByBroadcast()（遍历所有handler，同时推送云端+前端）',
        '   适用于：过滤链中跳过回执匹配的被动消息（未被设置flowSource）',
        '   例如：非本人发送的recvmsg、系统通知等',
      ].join('\n'),
      dataIn: 'jsonObject（含 flowSource 字段）+ finalMessage（JSON字符串）+ pipeLineWrapper',
      dataOut: '路由到 cloudFlowOutBound 或 frontFlowOutBound',
      logKeywords: ['businessHandler', 'flowSource', 'outBoundByBroadcast'],
      logQuery: '搜索 businessHandler + source=',
      cacheOps: '',
      dbOps: '',
    },

    cloudFlowOut: {
      id: 'cloud_flow_out',
      name: '云端出站处理',
      icon: 'cloud-upload',
      file: 'src/msg-center/dispatch-center/dispatch/cloudFlowOutBound.js',
      func: 'cloudFlowOutBound(message, pipeLineWrapper)',
      lines: '',
      summary: '遍历 convert-service/convert-response 列表，按 registry.workWx 选择平台列表，filter()匹配→operate()执行→MQTT上报云端',
      arrow: 'filter() → operate()',
      detail: [
        '处理流程:',
        '1. 按平台选择 service 列表:',
        '   [微信]  WxConvertServiceList  (16项) + WxConvertResponseList',
        '   [企微]  WorkWxConvertServiceList (25项) + WorkWxConvertResponseList',
        '2. 遍历列表，对每个 handler 调用 filter(message):',
        '   → filter() 返回 true: 调用 operate(message, wrapper)',
        '   → operate() 内完成数据转换 + mqttSend 上报云端',
        '',
        'convert-service: 处理被动事件（被动消息接收、好友请求、群变动等）',
        '  例: recvMsgService.filter() 匹配 recvmsg/recvmsgs',
        '  → operate() 解析消息内容 → mqttSend 上报云端',
        '',
        'convert-response: 处理主动任务的执行结果',
        '  例: sendMsgConvert.filter() 匹配任务回执',
        '  → operate() 组装结果 → mqttSend 上报云端',
        '',
        '部分 convert-service 的 operate() 内还会触发 HTTP 上传:',
        '  如 uploadUserListService → 调用 httpClient 上传好友/群列表',
        '（详细处理器清单见步骤4的任务列表）',
      ].join('\n'),
      dataIn: '逆向回报消息 (含完整上下文)',
      dataOut: '转换后的云端消息格式',
      logKeywords: ['cloudFlowOutBound', 'convert-service', 'convert-response'],
      logQuery: '搜索对应 convert-service/response 名称 + wxid',
      cacheOps: '',
      dbOps: '',
    },

    mqttPublish: {
      id: 'mqtt_publish',
      name: 'MQTT上报云端',
      icon: 'cloud-upload',
      file: 'src/msg-center/dispatch-center/mqttSend.js → src/msg-center/core/mq/mqExcuteMsg.js',
      func: 'sendMessage() → mqExcuteMsg()',
      lines: '',
      summary: '将处理结果通过 MQTT publish 上报到云端',
      arrow: '',
      detail: [
        '1. mqttSend.getInstance().sendMessage(wxid, clientMsg):',
        '   - 填充 clientMsgSource、username、clientVersion 等字段',
        '2. mqExcuteMsg(wxid, topic, clientMsg):',
        '   - Topic: ApplicationEnv["parentTopic"] (如 robot-wx-win-pro)',
        '   - 若 MQTT 未初始化: 消息写入 MqttMakeUpManager 队列',
        '   - 正常: registry.mqttClient.publish(topic, Buffer.from(JSON.stringify(msg)))',
        '   - 异常: 调用 UploadMetricTask.run(wxId, Metric.MQTT_SEND_TIMEOUT)',
        '',
        '上报字段 (ClientMsg):',
        '  username, clientMsgSource(0=个微), type, taskInfo, recordInfo,',
        '  friendRequest, acceptFriendInfo, friendInfos, clientVersion, clientPushTime',
      ].join('\n'),
      dataIn: 'ClientMsg 对象',
      dataOut: 'MQTT publish payload (JSON Buffer)',
      logKeywords: ['MqttClientUtil-send', '上报MQTT', 'mqExcuteMsg', 'MQTT发往云端'],
      logQuery: '搜索: MqttClientUtil-send + wxid 或 上报MQTT任务结束 + taskId\n异常搜索: MQTT client未初始化完毕、MQTT发往云端数据异常',
      cacheOps: 'MqttMakeUpManager — MQTT未初始化时的消息队列',
      dbOps: '',
    },

    // ---------- 前端链路共享节点 ----------
    frontFlowIn: {
      id: 'front_flow_in',
      name: '前端入站处理',
      icon: 'monitor',
      file: 'src/msg-center/dispatch-center/dispatch/frontFlowInBound.js',
      func: 'frontFlowInBound(message)',
      lines: '',
      summary: '接收前端 WebSocket 消息，按 cmdId 路由到对应处理器',
      arrow: 'frontHandlerMap[cmdId]()',
      detail: [
        '1. 解析 WebSocket 消息中的 cmdId',
        '2. 按 cmdId 路由到 frontHandlerMap 中对应的处理函数',
        '3. 常见 cmdId:',
        '   - FORWARD: 转发到逆向 → forwardTask.js',
        '   - 其他前端专用指令',
      ].join('\n'),
      dataIn: 'WebSocket message (JSON)',
      dataOut: '路由到对应的前端任务处理器',
      logKeywords: ['frontFlowInBound', 'cmdId'],
      logQuery: '搜索 frontFlowInBound + cmdId',
      cacheOps: '',
      dbOps: '',
    },

    frontFlowOut: {
      id: 'front_flow_out',
      name: '前端出站推送',
      icon: 'monitor',
      file: 'src/msg-center/dispatch-center/dispatch/frontFlowOutBound.js\nsrc/msg-center/business/point-cut/SendFrontAsect.js',
      func: 'frontFlowOutBound(message, pipeLineWrapper)',
      lines: '',
      summary: '将消息推送到 Electron 前端 UI。[企微] 先经 SendFrontAspect 切面拦截做类型转换（login/remark/kickout），命中则由策略处理不再透传；[微信] 直接透传。',
      arrow: 'sendToFront()',
      detail: [
        '处理流程:',
        '',
        '1. SendFrontAspect.beforeSendMessageToFront(message, wrapper):',
        '   [微信] workWx=false → 返回 isExit=false，不拦截',
        '   [企微] workWx=true → 遍历 3 个策略:',
        '     • SendKickOutMsgFrontStrategy — 踢出群成员消息，转换为前端格式',
        '     • SendLoginMsgFrontStrategy   — 登录消息，转换为前端格式',
        '     • SendRemarkMsgFrontStrategy  — 备注变更消息，转换为前端格式',
        '     任一策略 handleMsgToFront() 返回 true → isExit=true，消息已由策略处理',
        '',
        '2. 过滤 type===RECVMSG 类型（接收消息不推送前端）',
        '',
        '3. !isExit 时:',
        '   sendToFront(message, pipeLineWrapper.id, pipeLineWrapper.wxid)',
        '   → 通过 WebSocket 推送到 Electron 渲染进程',
        '',
        '另: SendFrontAspect.beforeSendFriendList() 单独处理好友列表:',
        '   企微格式(conversations+externalUsers) → 个人微信格式(chatroomList+friendList)',
      ].join('\n'),
      dataIn: '逆向回报消息 (JSON string)',
      dataOut: 'WebSocket 推送数据',
      logKeywords: ['frontFlowOutBound', 'sendToFront', 'SendFrontAspect'],
      logQuery: '搜索 frontFlowOutBound 或 sendToFront + wxid',
      cacheOps: '',
      dbOps: '',
    },
  };

  // ================================================================
  //  辅助函数
  // ================================================================

  function clone(obj) {
    return JSON.parse(JSON.stringify(obj));
  }

  function buildDownstreamFlow(name, handler, options) {
    var steps = [
      clone(INFRA.mqttRecv),
      clone(INFRA.mqttRoute),
      handler,
      clone(INFRA.cloudFlowIn),
      clone(INFRA.dispatchIn),
      clone(INFRA.reverseSend),
      clone(INFRA.wechatDown),
    ];
    return { name: name, direction: 'downstream', steps: steps };
  }

  function buildUpstreamFlow(name, convertHandler, options) {
    var steps = [
      clone(INFRA.wechatUp),
      clone(INFRA.ipcPoll),
      clone(INFRA.dispatchOut),
      clone(INFRA.msgHandle),
      clone(INFRA.businessRoute),
      clone(INFRA.cloudFlowOut),
      convertHandler,
      clone(INFRA.mqttPublish),
    ];
    return { name: name, direction: 'upstream', steps: steps };
  }

  function buildEventUpstreamFlow(name, convertHandler) {
    var steps = [
      clone(INFRA.wechatUp),
      clone(INFRA.ipcPoll),
      clone(INFRA.dispatchOut),
      convertHandler,
      clone(INFRA.mqttPublish),
    ];
    return { name: name, direction: 'upstream-event', steps: steps };
  }


  window._GCData.INFRA = INFRA;
  window._GCData.clone = clone;
  window._GCData.buildDownstreamFlow = buildDownstreamFlow;
  window._GCData.buildUpstreamFlow = buildUpstreamFlow;
  window._GCData.buildEventUpstreamFlow = buildEventUpstreamFlow;
})();
